# Generated by Django 3.2.20 on 2023-07-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
