# Generated by Django 3.2.20 on 2023-07-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customerss'},
        ),
    ]
