# Generated by Django 3.2.20 on 2023-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Status',
            field=models.BooleanField(default=True),
        ),
    ]
