# Generated by Django 3.2.20 on 2023-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Status',
            field=models.BooleanField(default=False),
        ),
    ]
