# Generated by Django 3.2.20 on 2023-07-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Customer_Address',
            new_name='employee_Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Customer_Status',
            new_name='employee_Status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Customer_email',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Customer_mobile',
            new_name='employee_mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Customer_name',
            new_name='employee_name',
        ),
    ]
